version: '3.3'
services:
  mydb:
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=tmx
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    image: mysql