version: '3.3'
services:
  mydb:
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=tmx
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    image: mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  vipdb: 